# Dependencies options
set(ROBOTOLOGY_USES_GAZEBO ON CACHE BOOL "")
set(ROBOTOLOGY_USES_GZ ON CACHE BOOL "")
set(ROBOTOLOGY_USES_PCL_AND_VTK ON CACHE BOOL "")
set(ROBOTOLOGY_USES_OCTAVE ON CACHE BOOL "")
set(ROBOTOLOGY_USES_PYTHON ON CACHE BOOL "")
set(ROBOTOLOGY_USES_MATLAB ON CACHE BOOL "")
set(ROBOTOLOGY_USES_CFW2CAN ON CACHE BOOL "")
set(ROBOTOLOGY_USES_ESDCAN ON CACHE BOOL "")
set(ROBOTOLOGY_USES_XSENS_MVN_SDK ON CACHE BOOL "")

# Profiles options
set(ROBOTOLOGY_ENABLE_ROBOT_TESTING ON CACHE BOOL "")
set(ROBOTOLOGY_ENABLE_DYNAMICS ON CACHE BOOL "")
set(ROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS ON CACHE BOOL "")
set(ROBOTOLOGY_ENABLE_HUMAN_DYNAMICS ON CACHE BOOL "")
set(ROBOTOLOGY_ENABLE_ICUB_HEAD ON CACHE BOOL "")
set(ROBOTOLOGY_ENABLE_ICUB_BASIC_DEMOS ON CACHE BOOL "")
set(ROBOTOLOGY_ENABLE_TELEOPERATION ON CACHE BOOL "")
set(ROBOTOLOGY_ENABLE_EVENT_DRIVEN ON CACHE BOOL "")
set(ROBOTOLOGY_ENABLE_GRASPING ON CACHE BOOL "")
set(ROBOTOLOGY_ENABLE_ROS2 ON CACHE BOOL "")
set(ROBOTOLOGY_ENABLE_MOVEIT  ON CACHE BOOL "")

# Internal profile
set(ROBOTOLOGY_INTERNAL_CLONE_ALL_REPOS_FOR_UPDATE ON CACHE BOOL "")
# all-options-enabled-cache.cmake is usd by the update-latest-releases action,
# that requires repos to be cloned in a non-shallow way. So here we override
# also the shallow options for the repos that have shallow enabled
set(icub-firmware-build_SHALLOW ON CACHE BOOL "")
