# bipedal-locomotion-framework requires 10.13 for std::bad_cast_any
# robometry requeries 10.15 for std::filesystem
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - 10.15                      # [osx and x86_64]

qt:
  - 5.15

qt_main:
  - 5.15

# Remove once the fmt121_spdlog117 conda-forge migration is completed,
# see https://github.com/gbionics/walking-controllers/issues/208#issuecomment-3916889576
fmt:
  - '12.1'
spdlog:
  - '1.17'

# Remove once the migration to eigen 5 is finished
eigen:
  - '3.4.0'
