{{ '{% set name =' }} "{{ name }}" {{ '%}' }}

package:
{% raw %}  name: {{ name }} {% endraw %}
  version: "{{ version.replace("v","").replace("release-","") }}"

source:
  git_url: https://github.com/{{ github_repo }}.git
  git_rev: {{ github_tag }}

build:
  number: {{ conda_build_number }}
  run_exports:
{% raw %}    # As robotology-superbuild packages tipically do not worry about ABI compatibility,
    # we explicitly specify that for every patch version the ABI changes
    - {{ pin_subpackage(name, max_pin='x.x.x') }}
{% endraw %}

requirements:
  build:
{# A C/C++ compiler and CMake are required by all packages #}
{% raw %}    - {{ compiler('c') }}
    - {{ compiler('cxx') }} {% endraw %}
    - cmake
    - pkg-config
    - ninja
{% for build_dep in build_dependencies_explicit %}    - {{ build_dep }}
{% endfor %}
{# Handle specific packages required for gl on Linux, see https://conda-forge.org/docs/maintainer/knowledge_base.html?#libgl and https://github.com/conda-forge/qt-main-feedstock/blob/0a0caca0eef18d4f895ec81840dcb037a20dc844/recipe/meta.yaml#L67-L158 #}
{% if require_opengl_linux %}{% raw %}    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-dri-drivers') }}
    - {{ cdt('libselinux') }}  {% endraw %}{% endif %}


  host:
{# List all dependencies just a host. Run dependenencies should be correctly set by run_exports, except the one listed in #}
{% for dep in dependencies %}    - {{ dep }}
{% endfor %}
{# Handle specific packages required for gl on Linux, see https://conda-forge.org/docs/maintainer/knowledge_base.html?#libgl and https://github.com/conda-forge/qt-main-feedstock/blob/0a0caca0eef18d4f895ec81840dcb037a20dc844/recipe/meta.yaml#L67-L158 #}
{# libxcb, libxfixes and libxau are not documented anywhere, but without those blocktest does not build correctly #}
{# xorg-libxrandr is actually needed by glfw 3.4 #}
{% if require_opengl_linux %}    - xorg-libxfixes
    - xorg-libxdamage
    - xorg-libxxf86vm
    - xorg-libxext
    - xorg-libxau
    - libxcb
    - xorg-libxrandr 
    - xorg-libxfixes {% endif %}
{# Handle the constraint of macos >= 10.13 #}
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
{# List additional run dependencies that are not covered by run_exports #}
{% for dep in run_dependencies_explicit %}    - {{ dep }}
{% endfor %}
{% if add_python_runtime_dep %}    - python {% endif %}
{% if add_numpy_runtime_dep %}{% raw %}    - {{ pin_compatible('numpy') }}  {% endraw %}{% endif %}

about:
  home: https://github.com/{{ github_repo }}
