schema_version: 1

context:
  name: vvv-school-activation
  version: 1.0.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  # dummy, I only use it to get the LICENSE file
  - url: https://github.com/ami-iit/resolve-robotics-uri-py/archive/refs/tags/v0.3.0.zip
    sha256: d28e51bfa3ffe87e32cc97fa443d1886e98fd823d2e21492d9dbb96778c97506

build:
  number: 0

requirements:
  build:
    - multisheller

tests:
  - script:
      - if: unix
        then: test -f ${PREFIX}/etc/conda/activate.d/vvv-school-activation_activate.sh
      - if: unix
        then: test -f ${PREFIX}/etc/conda/deactivate.d/vvv-school-activation_deactivate.sh
      - if: win
        then: if not exist %PREFIX%\\etc\\conda\\activate.d\\vvv-school-activation_activate.bat exit 1
      - if: win
        then: if not exist %PREFIX%\\etc\\conda\\deactivate.d\\vvv-school-activation_deactivate.bat exit 1

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Helper package that set environment variables required by vvv-school repositories in the activation scripts.
  description: |
    For more info, check https://github.com/vvv-school/vvv-school.github.io/blob/master/instructions/how-to-create-conda-environment-for-school.md .


  homepage: https://github.com/vvv-school

extra:
  recipe-maintainers:
    - traversaro
