{{ '{% set name =' }} "{{ name }}" {{ '%}' }}

package:
{% raw %}  name: {{ name }} {% endraw %}
  version: "{{ version.replace("v","") }}"

source:
  git_url: https://github.com/{{ github_repo }}.git
  git_rev: {{ github_tag }}

build:
  noarch: python
  # Due to robot-log-visualizer, drop when conda-forge does not uses Python 3.7 anymore
  skip: True  # [py<38]
  number: {{ conda_build_number }}
{% raw %}  script: {{ PYTHON }} -m pip install . --no-deps -vv {% endraw %}
  entry_points:
{% for entry_point in entry_points %}    - {{ entry_point }}
{% endfor %}

requirements:
  build:

  host:
    - python
    - pip
    - setuptools-scm
{% for dep in dependencies %}    - {{ dep }}
{% endfor %}
  run:
    - python
{% for dep in dependencies %}    - {{ dep }}
{% endfor %}

test:
  commands:
    # Do not run pip check on arm64 as pip list does not list qtpy5 and qtwebengine
    - pip check  # [not arm64]
  requires:
    - pip

about:
  home: https://github.com/{{ github_repo }}
